name: Setup Python and Poetry
author: Renumics GmbH
description: Set up Python and Poetry environment, cache/restore dependencies
inputs:
  os:
    description: "OS"
    required: true
  python-version:
    description: "Python version to set up"
    required: true
  poetry-version:
    description: "Poetry version to set up"
    default: "2.2.1"
runs:
  using: composite
  steps:
    - name: Set up Poetry ${{ inputs.poetry-version }}
      run: |
        pipx install 'poetry==${{ inputs.poetry-version }}'
        pipx inject poetry poetry-dynamic-versioning
      shell: bash
    - name: Set up Python ${{ inputs.python-version }}
      id: setup-python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry
    - name: Install dependencies
      if: steps.setup-python.outputs.cache-hit != 'true'
      run: poetry sync --no-interaction
      shell: bash
